/* Source-aligned command catalog for the STARS System Bot website. */
(() => {
  const categories = {
    all: { icon: '✦', color: '#8b5cf6', en: 'All commands', ar: 'كل الأوامر' },
    general: { icon: '✨', color: '#35d5f5', en: 'General', ar: 'العامة' },
    moderation: { icon: '🛡️', color: '#fb7185', en: 'Moderation', ar: 'الإشراف' },
    leveling: { icon: '📈', color: '#34d399', en: 'Leveling', ar: 'المستويات' },
    automation: { icon: '⚡', color: '#8b5cf6', en: 'Automation', ar: 'الأتمتة' },
    community: { icon: '🎉', color: '#f472b6', en: 'Community', ar: 'المجتمع' },
    owner: { icon: '⚙️', color: '#fbbf24', en: 'Owner', ar: 'المالك' },
    tickets: { icon: '🎫', color: '#5b8cff', en: 'Tickets', ar: 'التذاكر' },
  };

  const permissions = {
    everyone: { color: '#34d399', en: 'Everyone', ar: 'الجميع' },
    owner: { color: '#fbbf24', en: 'Bot owner', ar: 'مالك البوت' },
    staff: { color: '#35d5f5', en: 'Ticket staff', ar: 'طاقم التذاكر' },
    admin: { color: '#f472b6', en: 'Administrator', ar: 'الإدارة' },
    timeout: { color: '#fb7185', en: 'Timeout Members', ar: 'إيقاف الأعضاء مؤقتاً' },
    ban: { color: '#fb7185', en: 'Ban Members', ar: 'حظر الأعضاء' },
    kick: { color: '#fb7185', en: 'Kick Members', ar: 'طرد الأعضاء' },
    messages: { color: '#fb7185', en: 'Manage Messages', ar: 'إدارة الرسائل' },
    channels: { color: '#fb7185', en: 'Manage Channels', ar: 'إدارة القنوات' },
  };

  const command = (id, category, mode, permission, slash, prefix, example, aliases, en, ar, note = null) => ({
    id, category, mode, permission, slash, prefix, example, aliases, text: { en, ar }, note,
  });

  const commands = [
    command('help','general','both','everyone','/help','!help','/help',['h','commands'],'Opens the interactive command center with category buttons and command usage.','يفتح مركز الأوامر التفاعلي مع أزرار التصنيفات وطريقة استخدام كل أمر.'),
    command('user','general','both','everyone','/user user:<optional>','!user [@member]','/user user:@Nova',['u','whois','userinfo'],'Shows account ID, nickname, dates, highest role, server roles, bot status, and boost status.','يعرض معرف الحساب واللقب والتواريخ وأعلى رتبة ورتب السيرفر وحالة البوت والبوست.'),
    command('server','general','both','everyone','/server','!server','/server',['s','serverinfo'],'Shows detailed server identity, owner, verification, members, channels, roles, emojis, boosts, and features.','يعرض تفاصيل السيرفر والمالك والتحقق والأعضاء والقنوات والرتب والإيموجيات والبوستات والمميزات.'),
    command('boostinfo','general','both','everyone','/boostinfo user:<optional>','!boostinfo [@member]','/boostinfo user:@Nova',['boost','boosting'],'Builds a polished boost profile with start date, current badge, duration, next milestone, and a progress image.','ينشئ ملف بوست احترافي يحتوي تاريخ البداية والشارة الحالية والمدة والمرحلة القادمة وصورة التقدم.'),
    command('nitroinfo','general','both','everyone','/nitroinfo user:<optional>','!nitroinfo [@member]','/nitroinfo user:@Nova',['nitro'],'Shows the member Nitro progression, active rank, unlocked badges, next rank date, and Canvas progress card.','يعرض تقدم نيترو للعضو والرتبة الحالية والشارات المفتوحة وتاريخ الرتبة القادمة وبطاقة التقدم.'),

    command('rank','leveling','both','everyone','/rank user:<optional>','!rank [@member]','/rank',['levelrank','myrank','r','xp','xpinfo','levelprofile'],'Displays level, total XP, server position, eligible messages, remaining XP, progress bar, and next reward.','يعرض المستوى وإجمالي الخبرة والترتيب والرسائل المحتسبة والخبرة المتبقية وشريط التقدم والمكافأة القادمة.'),
    command('top','leveling','both','everyone','/top','!top','/top',['leaderboard','lb','toplevel','topxp','xptop'],'Shows the server top 10 leaderboard as real member mentions with level, XP, and message totals.','يعرض أفضل 10 أعضاء في السيرفر كمنشن حقيقي مع المستوى والخبرة وعدد الرسائل.'),
    command('level','leveling','both','owner','/level <subcommand>','!level <action>','/level reward-set level:10 role:@Veteran',['levels','levelconfig'],'Advanced XP control center: enable state, channel/role filters, announcements, XP range, cooldown, rewards, and resets.','مركز تحكم متقدم بالخبرة: التفعيل وفلاتر القنوات والرتب والإعلانات ونطاق الخبرة والانتظار والمكافآت والتصفير.',{en:'Subcommands: status, enabled, announcement, enabled/disabled channel or role, reward-set/remove, xp, reset-user, reset-all.',ar:'الأوامر الفرعية: الحالة والتفعيل والإعلان وفلاتر القنوات والرتب والمكافآت والخبرة وتصفير عضو أو الجميع.'}),

    command('mute','moderation','both','timeout','/mute user:<member> duration:<time> reason:<optional>','!mute @member 1h [reason]','/mute user:@Member duration:30m reason:Spam',['m'],'Temporarily prevents a member from interacting for a duration up to Discord’s 28-day limit.','يمنع العضو مؤقتاً من التفاعل لمدة تصل إلى حد ديسكورد الأقصى 28 يوماً.'),
    command('timeout','moderation','both','timeout','/timeout user:<member> duration:<time> reason:<optional>','!timeout @member 1h [reason]','/timeout user:@Member duration:2h reason:Rule violation',['to'],'Applies a Discord timeout with duration parsing, hierarchy checks, and an optional audit reason.','يطبق تايم أوت مع قراءة المدة والتحقق من ترتيب الرتب وسبب اختياري.'),
    command('ban','moderation','both','ban','/ban user:<member> reason:<optional>','!ban @member [reason]','/ban user:@Member reason:Repeated violations',['b'],'Bans a member after checking moderator permission and both user and bot role hierarchy.','يحظر عضواً بعد التحقق من صلاحية المشرف وترتيب رتب المستخدم والبوت.'),
    command('unban','moderation','both','ban','/unban user_id:<id> reason:<optional>','!unban <user ID> [reason]','/unban user_id:123456789012345678 reason:Appeal accepted',['ub'],'Removes a server ban using the exact Discord user ID and records an optional reason.','يلغي حظر مستخدم بواسطة معرف ديسكورد الكامل مع سبب اختياري.'),
    command('kick','moderation','both','kick','/kick user:<member> reason:<optional>','!kick @member [reason]','/kick user:@Member reason:Warnings ignored',['k'],'Kicks a member with permission, hierarchy, and bot-role safety validation.','يطرد عضواً مع التحقق من الصلاحية وترتيب الرتب وقدرة رتبة البوت.'),
    command('lock','moderation','both','channels','/lock','!lock','/lock',['close'],'Locks the current channel and safely saves its previous @everyone Send Messages state.','يقفل القناة الحالية ويحفظ حالة صلاحية إرسال الرسائل السابقة لرتبة الجميع بأمان.'),
    command('unlock','moderation','both','channels','/unlock','!unlock','/unlock',['open'],'Restores the exact channel permission state saved by the bot’s lock command.','يعيد حالة صلاحيات القناة نفسها التي حفظها أمر القفل.'),
    command('clear','moderation','both','messages','/clear amount:<1-100>','!clear <1-100>','/clear amount:50',['purge'],'Bulk deletes between 1 and 100 recent messages in the current channel.','يحذف دفعة من 1 إلى 100 رسالة حديثة في القناة الحالية.'),

    command('line','automation','both','owner','/line channel:<text> image:<file> image_url:<url>','!line #channel <image URL>','/line channel:#chat image_url:https://example.com/line.png',['autoline'],'Sets a raw image line that the bot sends after every normal user message in a selected channel.','يضبط صورة خط يرسلها البوت بعد كل رسالة عادية في القناة المحددة.'),
    command('unline','automation','both','owner','/unline channel:<optional>','!unline [#channel]','/unline channel:#chat',['removeline','stopline'],'Removes automatic image-line behavior from the selected or current channel.','يلغي إرسال صورة الخط التلقائية من القناة المحددة أو الحالية.'),
    command('mention','automation','both','owner','/mention <set|list|clear>','!mention #channel @role <message>','/mention set channel:#news role:@Updates message:New post!',['automentions','rolemention'],'Sends a configured role mention and message after activity in a channel, with restricted allowed mentions.','يرسل منشن رتبة ورسالة محددة بعد النشاط في قناة مع تقييد المنشنات المسموحة.'),
    command('welcome','automation','both','owner','/welcome channel:<optional> enabled:<optional>','!welcome #channel true','/welcome channel:#welcome enabled:true',['welcomeset','welcomechannel'],'Configures the member welcome channel and branded welcome Canvas using the member avatar and username.','يضبط قناة ترحيب الأعضاء وصورة الترحيب التي تحتوي صورة العضو واسمه.'),
    command('boostwelcome','automation','both','owner','/boostwelcome channel:<optional> enabled:<optional>','!boostwelcome #channel true','/boostwelcome channel:#boosts enabled:true',['boostset','boostchannel'],'Configures localized booster thanks messages and branded avatar welcome artwork.','يضبط رسائل شكر البوستر المترجمة وصورة الترحيب المميزة مع صورة العضو.'),
    command('auto','automation','both','owner','/auto <set|remove|status>','!auto set <human|bot> @role','/auto set type:human role:@Members',['autorole','joinrole'],'Assigns separate configured roles automatically when human members or bot accounts join.','يعطي رتباً منفصلة تلقائياً عند دخول أعضاء حقيقيين أو حسابات بوت.'),
    command('automsg','automation','both','owner','/automsg channel:<text> time:<duration> message:<text>','!automsg #channel 1h <message>','/automsg channel:#news time:1h message:Remember to vote!',['automessage','schedulemsg'],'Creates a persistent recurring message schedule using durations such as 30m, 1h, or 1d.','ينشئ جدولة دائمة لرسالة متكررة باستخدام مدة مثل 30 دقيقة أو ساعة أو يوم.'),
    command('automsglist','automation','both','owner','/automsglist','!automsglist','/automsglist',['automessages','schedulelist'],'Lists every recurring message schedule, its channel, interval, identifier, and next delivery.','يعرض كل الرسائل المجدولة وقنواتها وفتراتها ومعرفاتها وموعد الإرسال القادم.'),
    command('automsgremove','automation','both','owner','/automsgremove id:<schedule ID>','!automsgremove <schedule ID>','/automsgremove id:A1B2C3D4E5F6',['automsgdelete','scheduledelete'],'Permanently removes the recurring message schedule matching the displayed 12-character ID.','يحذف نهائياً جدولة الرسالة المطابقة للمعرف المعروض المكون من 12 حرفاً.'),
    command('reply','automation','slash','owner','/reply trigger:<text> response:<text>',null,'/reply trigger:hi response:Hello and welcome!',[],'Creates or updates an exact-match automatic reply for this server.','ينشئ أو يحدث رداً تلقائياً يعمل عند مطابقة النص المحدد تماماً.'),
    command('replylist','automation','slash','owner','/replylist',null,'/replylist',[],'Lists every automatic reply trigger and its configured response.','يعرض كل محفزات الرد التلقائي والردود المرتبطة بها.'),
    command('replyremove','automation','slash','owner','/replyremove trigger:<text>',null,'/replyremove trigger:hi',[],'Removes the automatic reply registered for an exact trigger.','يحذف الرد التلقائي المسجل للنص المطابق.'),
    command('automod','automation','both','owner','/automod <status|enable|disable|channel|user|role|domain>','!automod <action>','/automod domain action:Add domain:stars-metin2.com',['antilink','linkguard','links'],'Controls link security with protected channels and user, role, or domain whitelists.','يتحكم بحماية الروابط مع قنوات محمية وقوائم بيضاء للمستخدمين والرتب والنطاقات.',{en:'With no protected channels configured, all text channels are protected. Allowed domains also allow their subdomains.',ar:'عند عدم تحديد قنوات، تتم حماية كل القنوات النصية. النطاق المسموح يشمل نطاقاته الفرعية.'}),

    command('log','community','slash','owner','/log type:<event/group> channel:<text> enabled:<true|false>',null,'/log type:messages channel:#logs enabled:true',[],'Routes selected audit events or complete event groups to a chosen channel with detailed embeds.','يرسل أحداث السجل المحددة أو مجموعات الأحداث كاملة إلى قناة مختارة بإمبدات تفصيلية.'),
    command('tempset','community','slash','owner','/tempset channel:<voice> channelcontrols:<text> enabled:<boolean>',null,'/tempset channel:➕ Create Room channelcontrols:#voice-controls enabled:true',[],'Configures join-to-create temporary voice rooms and one persistent button control interface.','يضبط غرف الصوت المؤقتة عند الدخول ولوحة تحكم واحدة دائمة بالأزرار.'),
    command('giveaway','community','slash','owner','/giveaway name:<title> time:<duration> price:<prize> winners:<1-20>',null,'/giveaway name:Nitro time:1d price:1 Month Nitro winners:2',[],'Starts a persistent timed giveaway with Join/Leave buttons, entrant count, host, prize, and multiple winners.','يبدأ مسابقة مؤقتة دائمة بأزرار دخول وخروج وعدد المشاركين والمستضيف والجائزة وعدة فائزين.'),
    command('giveawaycancel','community','slash','owner','/giveawaycancel giveaway_id:<optional>',null,'/giveawaycancel giveaway_id:AB12CD34',[],'Cancels an active giveaway, preserves its entrants, and disables the original controls without choosing winners.','يلغي مسابقة نشطة ويحفظ المشاركين ويعطل أزرارها الأصلية من دون اختيار فائزين.'),
    command('quote','community','slash','owner','/quote channel:<text> enabled:<boolean> reactions:<optional>',null,'/quote channel:#quotes enabled:true reactions:❤️ ⭐',[],'Turns messages into branded quote Canvas images with configured reactions and safe text fitting.','يحول الرسائل إلى صور اقتباس تحمل هوية STARS مع تفاعلات محددة وضبط آمن للنص.'),
    command('applyset','community','slash','owner','/applyset section:<name> button:<label> logs:<channel> admin_role:<role> question_1…5',null,'/applyset section:GM button:Apply logs:#applications admin_role:@Reviewers question_1:Your name?',[],'Creates or updates one of up to 25 application sections with a modal, review log, and Accept/Reject controls.','ينشئ أو يحدث واحداً من 25 قسم تقديم كحد أقصى مع نموذج وسجل مراجعة وأزرار قبول ورفض.'),
    command('applyremove','community','slash','owner','/applyremove section:<autocomplete>',null,'/applyremove section:GM',[],'Removes a configured application section and refreshes its shared panel.','يحذف قسم تقديم مضبوطاً ويحدث لوحة التقديم المشتركة.'),
    command('applylist','community','slash','owner','/applylist',null,'/applylist',[],'Lists application sections, buttons, review channels, reviewer roles, and question counts.','يعرض أقسام التقديم والأزرار وقنوات المراجعة ورتب المراجعين وعدد الأسئلة.'),

    command('blackadd','owner','both','owner','/blackadd word:<word or phrase>','!blackadd <word or phrase>','/blackadd word:blocked phrase',['blacklistadd'],'Adds a word or phrase to the global chat blacklist file.','يضيف كلمة أو عبارة إلى ملف الكلمات المحظورة العام.'),
    command('blackremove','owner','both','owner','/blackremove word:<word or phrase>','!blackremove <word or phrase>','/blackremove word:blocked phrase',['blacklistremove','blackdel'],'Removes an exact word or phrase from the chat blacklist.','يحذف كلمة أو عبارة مطابقة من قائمة الكلمات المحظورة.'),
    command('backwhite','owner','both','owner','/backwhite action:<Add|Remove|List> user:<optional>','!backwhite <add|remove|list> [@user]','/backwhite action:Add user:@Trusted',['blackwhite','blackwhitelist'],'Manages members allowed to use otherwise blacklisted words.','يدير الأعضاء المسموح لهم باستخدام الكلمات المحظورة.'),
    command('setprefix','owner','both','owner','/setprefix prefix:<1-5 chars>','!setprefix <prefix>','/setprefix prefix:?',['prefix'],'Changes this server’s prefix while keeping slash commands unchanged.','يغير بادئة أوامر هذا السيرفر مع بقاء أوامر السلاش كما هي.'),
    command('setalias','owner','both','owner','/setalias alias:<new> command:<existing>','!setalias <alias> <command>','/setalias alias:leaders command:top',['alias'],'Creates a custom server-specific prefix alias pointing to an existing command.','ينشئ اسماً بديلاً مخصصاً لأمر البادئة داخل هذا السيرفر.'),
    command('removealias','owner','both','owner','/removealias alias:<name>','!removealias <alias>','/removealias alias:leaders',['unalias','delalias'],'Deletes a custom prefix alias from this server.','يحذف اسماً بديلاً مخصصاً لأوامر البادئة من السيرفر.'),
    command('settings','owner','both','owner','/settings','!settings','/settings',['config'],'Shows current prefix, selected language, and every custom alias for the server.','يعرض البادئة الحالية واللغة المختارة وكل الأسماء البديلة المخصصة للسيرفر.'),
    command('lang','owner','both','owner','/lang language:<en|ar>','!lang <en|ar>','/lang language:ar',['language','setlanguage'],'Switches all supported bot systems and replies between English and Arabic.','يبدل كل أنظمة البوت وردوده المدعومة بين العربية والإنجليزية.'),
    command('restart','owner','both','owner','/restart','!restart','/restart',['reboot'],'Safely stops the process after confirmation so PM2, Docker, or another manager can restart it.','يوقف العملية بأمان بعد التأكيد ليعيد PM2 أو Docker أو مدير العمليات تشغيلها.'),

    command('send_panel','tickets','slash','admin','/send_panel',null,'/send_panel',[],'Deploys or refreshes the main ticket panel in the current channel.','ينشر أو يحدث لوحة فتح التذاكر الرئيسية في القناة الحالية.'),
    command('add_section','tickets','slash','admin','/add_section <section options>',null,'/add_section name:Support role:@Support log:#ticket-logs',[],'Adds a ticket section with its support role, log channel, presentation style, image, and optional emoji.','يضيف قسم تذاكر مع رتبة الدعم وقناة السجل وطريقة العرض والصورة وإيموجي اختياري.'),
    command('delete_section','tickets','slash','admin','/delete_section section:<name>',null,'/delete_section section:Support',[],'Deletes a configured ticket section and updates the active panel.','يحذف قسم تذاكر مضبوطاً ويحدث اللوحة النشطة.'),
    command('edit_settings','tickets','slash','admin','/edit_settings <channels and panel options>',null,'/edit_settings category:Tickets logs:#ticket-logs',[],'Configures ticket category, central logs, background, line image, and button/menu display mode.','يضبط تصنيف التذاكر والسجلات والخلفية وصورة الخط وطريقة العرض بالأزرار أو القائمة.'),
    command('add_user','tickets','slash','staff','/add_user user:<member>',null,'/add_user user:@Member',[],'Grants a member access to the current ticket channel.','يمنح عضواً صلاحية الدخول إلى قناة التذكرة الحالية.'),
    command('remove_user','tickets','slash','staff','/remove_user user:<member>',null,'/remove_user user:@Member',[],'Removes a member’s access from the current ticket channel.','يزيل صلاحية دخول عضو من قناة التذكرة الحالية.'),
    command('blacklist','tickets','slash','admin','/blacklist <add|remove|list>',null,'/blacklist add user:@Member reason:Abuse',[],'Manages users blocked from opening tickets, including an optional reason and complete list.','يدير المستخدمين الممنوعين من فتح التذاكر مع سبب اختياري وقائمة كاملة.'),
    command('snippet','tickets','slash','staff','/snippet <add|remove|send|list>',null,'/snippet add name:greeting content:Hello! How can we help?',[],'Creates, lists, sends, or removes reusable quick responses for ticket staff.','ينشئ أو يعرض أو يرسل أو يحذف ردوداً سريعة قابلة لإعادة الاستخدام للطاقم.'),
    command('invoice','tickets','slash','staff','/invoice amount:<number> reason:<text>',null,'/invoice amount:25 reason:Premium service',[],'Creates a professional customer invoice with interactive payment confirmation.','ينشئ فاتورة احترافية للعميل مع تأكيد دفع تفاعلي.'),
    command('note','tickets','slash','staff','/note text:<staff note>',null,'/note text:Customer requested an escalation.',[],'Adds an internal note visible only to ticket staff.','يضيف ملاحظة داخلية لا تظهر إلا لطاقم التذاكر.'),
    command('stats','tickets','slash','admin','/stats',null,'/stats',[],'Displays staff performance statistics and a service leaderboard.','يعرض إحصائيات أداء الطاقم ولوحة ترتيب الخدمة.'),
    command('dashboard','tickets','slash','admin','/dashboard',null,'/dashboard',[],'Opens the interactive ticket configuration and analytics dashboard.','يفتح لوحة التحكم التفاعلية لإعدادات التذاكر والإحصائيات.'),
    command('setreviews','tickets','slash','admin','/setreviews channel:<text>',null,'/setreviews channel:#reviews',[],'Sets the public channel where completed ticket ratings and reviews are published.','يضبط القناة العامة التي تنشر فيها تقييمات ومراجعات التذاكر المكتملة.'),
    command('aitoggle','tickets','slash','admin','/aitoggle',null,'/aitoggle',[],'Turns the smart AI ticket auto-support feature on or off.','يفعل أو يعطل ميزة الدعم التلقائي الذكي للتذاكر.'),
    command('backup','tickets','slash','admin','/backup',null,'/backup',[],'Forces a manual backup of ticket configuration and database records.','ينشئ نسخة احتياطية يدوية فورية من إعدادات وسجلات قاعدة بيانات التذاكر.'),
    command('setlang','tickets','slash','owner','/setlang language:<English|Arabic>',null,'/setlang language:English',[],'Changes the ticket subsystem language setting.','يغير إعداد لغة نظام التذاكر.'),
  ];

  window.STARS_COMMANDS = { commands, categories, permissions };
})();
